#!/bin/sh

HOST_DIR=$(pwd)
echo "$HOST_DIR"

CMAKE=cmake

BUILD_DIR_DBG=$HOST_DIR/bin/debug
BUILD_DIR_OPT=$HOST_DIR/bin/opt
BUILD_DIR_OPTDBG=$HOST_DIR/bin/optwithdebug
BUILD_DIR_MINSZOPT=$HOST_DIR/bin/minsizeopt

$CMAKE -S $HOST_DIR -G Ninja -B $BUILD_DIR_DBG      -D CMAKE_C_COMPILER=gcc
$CMAKE -S $HOST_DIR -G Ninja -B $BUILD_DIR_OPT      -D CMAKE_C_COMPILER=gcc
$CMAKE -S $HOST_DIR -G Ninja -B $BUILD_DIR_OPTDBG   -D CMAKE_C_COMPILER=gcc
$CMAKE -S $HOST_DIR -G Ninja -B $BUILD_DIR_MINSZOPT -D CMAKE_C_COMPILER=gcc